
a=str(input("Enter string :"))
length=len(a)
while length>0:
    if a==a[::-1]:
        print("palindrome")
        break
    else:
        print("not palindrome")
        break
# flag:True
# a=input("Enter String :")

# length=len(a)
# i=0
# j=length-1
# while i<j:
  
#    if a[i]==a[j]:
#      i+=1
#      j-=1
#    else:
#      flag:False
#      i=j
# if flag:
#   print("the string is palindrome")     
# else:
#   print("Not a palindrome")
 
   

     

 

 



  



